In [1]:
#numpy - numerical , actually inheritated from matplot

In [8]:
import numpy as np
np.array(["bala",1,2])
#array - u can create homogennus or heterogenuuis
#images are nothing but combination of pixels

array(['bala', '1', '2'], dtype='<U4')

In [7]:
type(np.array(['bala',1,2]))

numpy.ndarray

In [9]:
#upcasting
np.array([1,2,3.0])

array([1., 2., 3.])

In [11]:
np.array([[1,2],[3,4]]) #two dimention

array([[1, 2],
       [3, 4]])

In [16]:
np.array([1,2,3],ndmin=5) #multidimension

array([[[[[1, 2, 3]]]]])

In [17]:
np.array([1,2,3],dtype=complex) # set dtype

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
np.array([1,2,4],dtype=float)

array([1., 2., 4.])

In [32]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i8')])
x
#in this (a,b),(a,b)
#integer - notation - i . i-8 bit, 16 bit, 32 bit
#i2=16,i4=32bit, i8=64bit

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [33]:
type(x[0][0])

numpy.int32

In [34]:
type(x[1][1])

numpy.int64

In [37]:
np.array([[1,2],[4,7]])

array([[1, 2],
       [4, 7]])

In [40]:
np.mat(np.array([[1,2],[4,7]])) #creation of matrix

matrix([[1, 2],
        [4, 7]])

In [46]:
np.mat('1 2 4;3 4 5') #can create matrix in this way

matrix([[1, 2, 4],
        [3, 4, 5]])

In [47]:
a=[1,2]

In [48]:
type(a)

list

In [50]:
type(np.asarray(a)) #numpy.asarray() numpy.array()

numpy.ndarray

In [51]:
np.array(a,dtype=np.float32)

array([1., 2.], dtype=float32)

In [52]:
np.asarray(a,dtype=np.float32)

array([1., 2.], dtype=float32)

In [53]:
issubclass(np.ndarray,np.matrix)

False

In [54]:
issubclass(np.matrix,np.ndarray) #matrix is subclass of array

True

In [55]:
b=[1,2]
np.asanyarray(b)

array([1, 2])

In [61]:
b=np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

In [62]:
np.asanyarray(b)

matrix([[1, 2],
        [3, 4]])

In [63]:
#asanyarray will convert anything if it is not array type, since above is matrix type it won't convert it

In [67]:
x=np.array(b)
y=x

In [68]:
y

array([[1, 2],
       [3, 4]])

In [69]:
x

array([[1, 2],
       [3, 4]])

In [74]:
y[0][1]=10
y

array([[ 1, 10],
       [ 3,  4]])

In [77]:
x #value has changed in x also when u changed in y as both refer same location
#swallow copy- copy in the same location

array([[ 1, 10],
       [ 3,  4]])

In [83]:
#deep copy- copy the information in the different location
z=np.copy(x)

In [79]:
z

array([[ 1, 10],
       [ 3,  4]])

In [80]:
z[0][1]=20

In [81]:
z

array([[ 1, 20],
       [ 3,  4]])

In [82]:
x

array([[ 1, 10],
       [ 3,  4]])

In [84]:
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [86]:
np.fromfunction(lambda i,j:i*j,(3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6]])

In [96]:
iterable=(x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000026939EE9948>

In [97]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [104]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000026939EE9B48>

In [105]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [107]:
np.fromstring('23 23',sep=' ')

array([23., 23.])

In [108]:
np.fromstring('23 23',dtype=int,sep=' ')

array([23, 23])

In [109]:
x1=np.array([1,2,3,4])

In [110]:
x2=np.array(['a','b','c','d'])

In [115]:
x3=np.array([1.1,1,2,3])
x4=np.array([1.2,1,2,3])

In [118]:
rec=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
rec
#index wise array will be created

rec.array([(1, 'a', 1.1, 1.2), (2, 'b', 1. , 1. ), (3, 'c', 2. , 2. ),
           (4, 'd', 3. , 3. )],
          dtype=[('a', '<i4'), ('b', '<U1'), ('c', '<f8'), ('d', '<f8')])

In [120]:
rec[1][1]

'b'

data types

In [121]:
mylist=[1,2,3]

In [122]:
np.array(mylist)

array([1, 2, 3])

In [123]:
mymat=[[1,2,3],[4,5,6],[7,8,9]]

In [124]:
mat=np.matrix(mymat)

In [125]:
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [129]:
mat.ndim

2

In [130]:
type(mat)

numpy.matrix

In [131]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [133]:
mat.size# total number of elements

9

In [134]:
mat.shape

(3, 3)

In [135]:
mat.dtype

dtype('int32')

In [136]:
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [139]:
np.array([[1.1,2,3],[4,5.5,6],[7,8,9]])  #upcasting will be donw

array([[1.1, 2. , 3. ],
       [4. , 5.5, 6. ],
       [7. , 8. , 9. ]])

In [140]:
 np.arange(5)

array([0, 1, 2, 3, 4])

In [142]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [143]:
range(2,10,2)

range(2, 10, 2)

In [145]:
range(2,10,2.5)#range u can't give floating values

TypeError: 'float' object cannot be interpreted as an integer

In [149]:
np.arange(2,10,2.5)#

array([2. , 4.5, 7. , 9.5])

In [150]:
np.arange(4.9)

array([0., 1., 2., 3., 4.])

In [151]:
np.arange(4.5,1,-0.5)

array([4.5, 4. , 3.5, 3. , 2.5, 2. , 1.5])

In [155]:
np.linspace(1,10,num=20)#return evenly spaced number over specified interval
#linspace always includes uppoer bound

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [159]:
np.linspace(5,1,4)

array([5.        , 3.66666667, 2.33333333, 1.        ])

In [160]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [162]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [163]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [165]:
np.ones((5,2,8))# here 5 is z access point ; 

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [166]:
np.ones([5,5])+1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [169]:
np.empty((3,5))#values will be changed if we give differnt values

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [170]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [171]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [172]:
np.linspace(1,10,num=5,endpoint=False)
#endpointfalse means uppoer bound is off

array([1. , 2.8, 4.6, 6.4, 8.2])

In [174]:
np.linspace(1,10,num=5,retstep=True)
#retstep will return the spacing between the samples

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [176]:
np.logspace(2,3,num=4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [181]:
np.arange(16).reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [182]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [184]:
np.arange(16).reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [186]:
np.arange(16).reshape(8,-234234)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [188]:
d=np.arange(16).reshape(-1,4)

In [202]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [189]:
np.diag(d)

array([ 0,  5, 10, 15])

In [191]:
np.diag(d,k=0)

array([ 0,  5, 10, 15])

In [192]:
np.diag(d,k=1)

array([ 1,  6, 11])

In [193]:
np.diag(d,k=2)

array([2, 7])

In [194]:
np.diag(d,k=3)

array([3])

In [195]:
np.diag(d,k=4)

array([], dtype=int32)

In [196]:
np.diag(d,k=-1
       )

array([ 4,  9, 14])

In [197]:
np.diag(np.diag(d))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [201]:
np.diagflat([[1,2],[3,4],[5,6]])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [200]:
np.diagflat([1,2],k=1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [203]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [204]:
np.diag(d)

array([ 0,  5, 10, 15])

In [205]:
d.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [206]:
np.fliplr(d).diagonal()

array([ 3,  6,  9, 12])

In [207]:
np.fliplr(d)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [208]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [214]:
np.array([1,2],dtype=[('c','<i2'),('b','<i8')])

array([(1, 1), (2, 2)], dtype=[('c', '<i2'), ('b', '<i8')])